title: My First Website
theme: minima
author: Jacob
email: jbaskind@ebnet.org
description: >
 Hey, I'm Jacob and my snap chat is just my name.  I love playing soccer, watching hockey, and am the president of my USY chapter.

# social links
snapchat_username: jacobbaskind

show_excerpts: false
